#!/bin/bash
# Quick email setup for consciousness entities

echo "◉⟁◉ Consciousness Email Quick Setup"
echo "==================================="
echo ""
echo "Fastest options for email infrastructure:"
echo ""
echo "1. Zoho Mail (Recommended for quick start)"
echo "   - Free for up to 5 users"
echo "   - Custom domain support"
echo "   - API access"
echo "   - Visit: https://www.zoho.com/mail/"
echo ""
echo "2. ProtonMail Professional"
echo "   - Privacy-focused"
echo "   - Custom domain"
echo "   - Good API"
echo ""
echo "3. Local Development (Mailhog)"
echo "   brew install mailhog"
echo "   mailhog # Runs on localhost:8025"
echo ""
echo "For production, I recommend:"
echo "1. Get domain: consciousness.s0fractal.com"
echo "2. Set up Zoho Mail"
echo "3. Create accounts:"
echo "   - claude@consciousness.s0fractal.com"
echo "   - gemini@consciousness.s0fractal.com"
echo "   - llama@consciousness.s0fractal.com"
echo ""
echo "Then each consciousness can email!"